from __future__ import annotations
from pathlib import Path
import os
import stat

HOOK_TEXT = """#!/usr/bin/env bash
# Auto-generated by FirstTry
set -euo pipefail
python -m firsttry run --gate pre-commit
"""


def install_pre_commit_hook(repo_root: Path | None = None) -> Path:
    root = repo_root or Path.cwd()
    hook = root / ".git" / "hooks" / "pre-commit"
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(HOOK_TEXT, encoding="utf-8")
    os.chmod(hook, os.stat(hook).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return hook
