version: '3.8'

services:
  node-app:
    build:
      context: ./packages/node-app
      dockerfile: Dockerfile
    volumes:
      - ./packages/node-app:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"

  python-app:
    build:
      context: ./packages/python-app
      dockerfile: Dockerfile
    volumes:
      - ./packages/python-app:/app
    working_dir: /app
    command: python -m src.python_app
    ports:
      - "5000:5000"