name: node-ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: node-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-workspaces:
    name: ${{ matrix.name }} (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    if: >
      (matrix.path == 'dashboard' && hashFiles('dashboard/package.json') != '') ||
      (matrix.path == 'vscode-extension' && hashFiles('vscode-extension/package.json') != '')
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dashboard
            path: dashboard
            node: '20'
          - name: vscode-extension
            path: vscode-extension
            node: '20'

    defaults:
      run:
        working-directory: ${{ matrix.path }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: ${{ matrix.path }}/package-lock.json

      - name: Install deps (ci if lockfile exists)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm i --no-audit --no-fund
          fi

      - name: Lint (if present)
        run: npm run --if-present lint

      - name: Typecheck (if present)
        run: npm run --if-present typecheck

      - name: Unit tests (if present)
        env:
          CI: true
        run: npm test --if-present --silent

      - name: Build (if present)
        run: npm run --if-present build

      - name: Upload coverage (if present)
        if: success() && (exists('${{ matrix.path }}/coverage/lcov.info') || exists('${{ matrix.path }}/coverage'))
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-coverage
          path: ${{ matrix.path }}/coverage
          if-no-files-found: ignore

      - name: Upload build artifact (optional)
        if: success() && (matrix.name == 'dashboard') && exists('build') || exists('.next')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-build
          path: |
            ${{ matrix.path }}/build
            ${{ matrix.path }}/.next
          if-no-files-found: ignore
